---
title: "Project Portfolio"
---

# Projects

## 1. Spotify User's Activity Analysis
- **Description:** Given a Spotify random user activity dataset, visualize important aspects of his app usage.

- **Code:** <a href="https://github.com/Gubato/gubato.github.io/blob/main/Projects/Spotify/Top%20Spotify%20tracks.ipynb" 
    target="_blank" style="
    background-color:#007BFF;
    color:white;
    padding:10px 15px;
    border-radius:5px;
    text-decoration:none;
    font-weight:bold;"> GitHub </a>

- [Watch full presentation](Projects/Spotify/Presentation.html) 

<iframe src="Projects/Spotify/Presentation.html"
            width="100%"
            height="600px"
            style="border:none;">
</iframe>

## 2. Call Center operators analysis
**Description:** Given a call history dataset, detect inefficient operators in a Call Center. You must take in count outliers and different clients, since every client will have different amount of incalls and outcalls.

**Code:** <a href="https://github.com/Gubato/gubato.github.io/blob/main/Projects/Call%20center%20operators/FP%20-%20Callcenter%20operators%20analysis.ipynb" 
    target="_blank" style="
    background-color:#007BFF;
    color:white;
    padding:10px 15px;
    border-radius:5px;
    text-decoration:none;
    font-weight:bold;"> GitHub </a>

**Dashboard**: <a href="https://public.tableau.com/app/profile/luis.gutierrez2670/viz/Dashboard_17469899994240/Dashboard1#2" 
    target="_blank" style="
    background-color:#007BFF;
    color:white;
    padding:10px 15px;
    border-radius:5px;
    text-decoration:none;
    font-weight:bold;"> Tableau </a> 

::: {raw-html}
<div class='tableauPlaceholder' id='viz1733859328293' style='position: relative'>
  <object class='tableauViz' style='width: 100%; height: 600px;'>
    <param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> 
    <param name='embed_code_version' value='3' /> 
    <param name='name' value='Dashboard_17469899994240/Dashboard1' />
    <param name='tabs' value='no' />
    <param name='toolbar' value='yes' />
  </object>
</div>
<script type='text/javascript'>
  var divElement = document.getElementById('viz1733859328293');
  var vizElement = divElement.getElementsByTagName('object')[0];
  vizElement.style.width = '100%';
  vizElement.style.height = '600px';
  var scriptElement = document.createElement('script');
  scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';
  vizElement.parentNode.insertBefore(scriptElement, vizElement);
</script>
:::

